
  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest

  - name: Remove not required packages
    ansible.builtin.dnf:
      autoremove: yes

  - name: Install latest Apache
    ansible.builtin.dnf:
      # name: httpd
      # Introduced package variables at base/group_vars/all --> Triggers ALL hosts
      name: "{{ packages }}"
      state: latest  

  - name: Start service httpd
    ansible.builtin.service:
      name: httpd
      # Try on first execution --> state: restarted
      state: started
      enabled: yes

  - name: Disable password authentication for SSH
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#PasswordAuthentication yes"
      line: "PasswordAuthentication no"
    register: sshd_config

  - name: Restart SSH deamon
    ansible.builtin.service:
      name: sshd
      state: restarted
    when: sshd_config.changed

