---
  - name: Upgrade all packages
    ansible.builtin.apt:
      update_cache: yes
      name: "*"
      state: latest

  - name: Remove non-required dependencies
    ansible.builtin.apt:
      autoremove: yes

  - name: Ensure server has same time as current timezone --> Europe/Madrid.
    ansible.builtin.shell: /home/melo/Workdir/timezonefix.sh
    
    
  - name: Ensure SSH is secured by passing modified file
    ansible.builtin.copy:
      src: /home/melo/Workdir/ssh_config
      dest: /etc/ssh/ssh_config
      owner: root
      group: root
      mode: u+rw,g-wx,o-wx
      backup: yes
      #mode: 0644
    register: sshd_config