---
- hosts: ubuntu
  vars:
    workdir1: /home/melo/Workdir
    sshdir: /etc/ssh

  tasks:

  - name: Upgrade all packages
    ansible.builtin.apt:
      update_cache: yes
      name: "*"
      state: latest

  - name: Remove non-required dependencies
    ansible.builtin.apt:
      autoremove: yes

  #- name: Ensure server has same time as current timezone --> Europe/Madrid.
  #  ansible.builtin.shell: "{{ workdir1 }}/timezonefix.sh"

  - name: Set timezone to Europe/Madrid
    community.general.timezone:
      name: Europe/Madrid
    
    
  - name: Ensure SSH is secured by passing modified file
    ansible.builtin.copy:
      src: "{{ workdir1 }}"/ssh_config
      dest: "{{ sshdir }}"/ssh_config
      owner: root
      group: root
      mode: u+rw,g-wx,o-wx
      backup: yes
      #mode: 0644
    register: sshd_config