---
- hosts: lab_vms
  become : yes
# This playbook contains basic tasks, my main focus is to get more familiar with how Ansible works as well as 
# creating a reasonably easy setup that can also be replicated on a production/homelab environment.

#OG way to declare tasks to be performed
#  tasks:
#    - import_tasks: tasks/dnf_start.yml

 #Now using roles --> Sort of "smaller tasks files"
  roles:
    - role: system