---
- hosts: lab_vms
  become : yes
# This playbook contains basic tasks, my main focus is to get more familiar with how Ansible works as well as 
# creating a reasonably easy setup that can also be replicated on a production/homelab environment.
  tasks:
  roles:
    - system

- hosts: ubuntu
  become : yes
# This part contains the configurations being applied for my minilab home server.
# More information on main README file 
  tasks:
    - name: Execute Ubuntu role
      include_role: 
        name: ubuntu
    