---
- name: Revisit to Ansible Playbooks
  hosts: lab_vms
  become : yes
# This playbook contains basic tasks, my main focus is to get more familiar with how Ansible works as well as 
# creating a reasonably easy setup that can also be replicated on a production/homelab environment.
  tasks:
    - import_tasks: tasks/dnf_start.yml