---
  - name: Disable password authentication for SSH
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#PasswordAuthentication yes"
      line: "PasswordAuthentication no"
    register: sshd_config

  - name: Restart SSH deamon
    ansible.builtin.service:
      name: sshd
      state: restarted
    when: sshd_config.changed