---
  - name: Disable password authentication for SSH
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^#PasswordAuthentication yes"
      line: "PasswordAuthentication no"
    #register: sshd_config
    notify: Restart SSH daemon
    # It will notify the handler everytime the file changes

  - meta: flush handlers 
  #force ansible to execute handler before (otherwise, it will do so after
  #all other steps are executed)

  